export interface HackathonEvent {
  eventId: string;
  eventName: string;
  maxTeamSize: number;
  minTeamSize: number;
  registrationDeadline: string;
  isPaid: boolean;
  fee: number;
}

export interface TeamMember {
  name: string;
  email: string;
  phone: string;
  collegeId: string;
  role: "lead" | "member";
}

export interface Team {
  teamId?: string; // Auto-generated by Firestore
  teamName: string;
  eventId: string;
  members: TeamMember[];
  status: "pending" | "otp_sent" | "verified" | "checked_in";
  createdAt?: any;
  updatedAt?: any;
  qrPayload?: string;
  qrSignatureExp?: any;
  teamCode?: string;
  deliveryStatus?: 'pending' | 'delivered' | 'failed';
  deliveredVia?: 'email' | 'whatsapp';
  deliveredAt?: any;
}

export interface UserRole {
  uid: string;
  email: string;
  role: "admin" | "volunteer";
  assignedGateId?: string;
  assignedEventId?: string;
}
